name: Build Web Frontend

on: push

jobs:
  build-web-frontend:
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm install
      working-directory: ./web-frontend
    - run: npm run build
      working-directory: ./web-frontend
